services:
  frontend:
    build: ./frontend
    networks:
      - movie-voting-net
    ports:
      - "5173:5173"
    depends_on:
      - backend
  backend:
    build: ./backend
    networks:
      - movie-voting-net
    ports:
      - "3000:3000"
    depends_on:
      - kafka
      - redis
  vote-processor:
    build: ./vote-processor
    networks:
      - movie-voting-net
    depends_on:
      - kafka
      - redis
  kafka:
    image: "confluentinc/cp-kafka:latest"
    networks:
      - movie-voting-net
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
  zookeeper:
    image: "confluentinc/cp-zookeeper:latest"
    networks:
      - movie-voting-net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
  redis:
    image: redis:latest
    networks:
      - movie-voting-net
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

networks:
  movie-voting-net:
    driver: bridge

volumes:
  redis-data: